# AWS SAM 模板文件
# 用于部署 Lambda 函数到 AWS

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 服装图片管理系统 - Lambda 后端

# 全局配置
Globals:
  Function:
    Runtime: nodejs18.x
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        S3_BUCKET_NAME: !Ref ImagesBucket
        SIGNED_URL_EXPIRATION: '86400'
        TZ: 'Asia/Tokyo'
        BRAND_TABLE_NAME: !Ref BrandTable

# 参数
Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
    Description: 部署环境

# 资源定义
Resources:
  BrandTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'PFTryonUserBrand-v2-${Environment}'
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: BrandId
          AttributeType: S
        - AttributeName: BrandName
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: BrandId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: BrandNameIndex
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
            - AttributeName: BrandName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # S3 存储桶（私有）
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'vrc-tryon-images-${Environment}'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda 上传处理函数
  PFTryonUploadTool:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'PFTryonUploadTool-${Environment}'
      Handler: index.handler
      CodeUri: PFTryonUploadTool/
      Description: PF Tryon - 处理图片上传到S3
      Timeout: 600
      MemorySize: 2048  # 增加到 2GB，获得更多 CPU 资源用于图片处理
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ImagesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref BrandTable
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
        UploadOptions:
          Type: Api
          Properties:
            Path: /upload
            Method: OPTIONS
            RestApiId: !Ref ApiGateway
        UploadPrepareApi:
          Type: Api
          Properties:
            Path: /upload/prepare
            Method: POST
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
        UploadPrepareOptions:
          Type: Api
          Properties:
            Path: /upload/prepare
            Method: OPTIONS
            RestApiId: !Ref ApiGateway
        UploadCompleteApi:
          Type: Api
          Properties:
            Path: /upload/complete
            Method: POST
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
        UploadCompleteOptions:
          Type: Api
          Properties:
            Path: /upload/complete
            Method: OPTIONS
            RestApiId: !Ref ApiGateway
        BrandListAllApi:
          Type: Api
          Properties:
            Path: /brand/listAll
            Method: POST
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
        BrandListAllOptions:
          Type: Api
          Properties:
            Path: /brand/listAll
            Method: OPTIONS
            RestApiId: !Ref ApiGateway
        ConfigPrepareApi:
          Type: Api
          Properties:
            Path: /config/prepare
            Method: POST
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
        ConfigPrepareOptions:
          Type: Api
          Properties:
            Path: /config/prepare
            Method: OPTIONS
            RestApiId: !Ref ApiGateway
        ConfigCompleteApi:
          Type: Api
          Properties:
            Path: /config/complete
            Method: POST
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
        ConfigCompleteOptions:
          Type: Api
          Properties:
            Path: /config/complete
            Method: OPTIONS
            RestApiId: !Ref ApiGateway

  # Lambda 列表获取函数
  PFTryonGetListTool:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'PFTryonGetListTool-${Environment}'
      Handler: index.handler
      CodeUri: PFTryonGetListTool/
      Description: PF Tryon - 获取图片列表
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ImagesBucket
      Events:
        ListApi:
          Type: Api
          Properties:
            Path: /list
            Method: POST
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
        ListOptions:
          Type: Api
          Properties:
            Path: /list
            Method: OPTIONS
            RestApiId: !Ref ApiGateway

  # Lambda 删除处理函数
  PFTryonDeleteTool:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'PFTryonDeleteTool-${Environment}'
      Handler: index.handler
      CodeUri: PFTryonDeleteTool/
      Description: PF Tryon - 删除S3中的图片
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ImagesBucket
      Events:
        DeleteApi:
          Type: Api
          Properties:
            Path: /delete
            Method: POST
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
        DeleteOptions:
          Type: Api
          Properties:
            Path: /delete
            Method: OPTIONS
            RestApiId: !Ref ApiGateway

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'vrc-tryon-api-${Environment}'
      StageName: !Ref Environment
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-api-key'"
        AllowMethods: "'GET,POST,OPTIONS,DELETE'"
        MaxAge: "'3000'"
      Auth:
        ApiKeyRequired: true
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/ap-northeast-1_XdS3QRCmQ'
            Identity:
              Header: Authorization

  # API Key
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - ApiGatewayStage
    Properties:
      Name: !Sub 'vrc-tryon-apikey-${Environment}'
      Description: PF Tryon API Key
      Enabled: true

  # Usage Plan
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ApiGatewayStage
    Properties:
      UsagePlanName: !Sub 'vrc-tryon-usage-plan-${Environment}'
      Description: PF Tryon Usage Plan
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref Environment
      Throttle:
        BurstLimit: 200
        RateLimit: 100
      Quota:
        Limit: 10000
        Period: DAY

  # Usage Plan Key - 将 API Key 关联到 Usage Plan
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

# 输出
Outputs:
  ApiUrl:
    Description: API Gateway 端点 URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  BucketName:
    Description: S3 存储桶名称
    Value: !Ref ImagesBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  PFTryonUploadToolArn:
    Description: 上传函数 ARN
    Value: !GetAtt PFTryonUploadTool.Arn

  PFTryonGetListToolArn:
    Description: 列表函数 ARN
    Value: !GetAtt PFTryonGetListTool.Arn

  PFTryonDeleteToolArn:
    Description: 删除函数 ARN
    Value: !GetAtt PFTryonDeleteTool.Arn

  ApiKeyId:
    Description: API Key ID
    Value: !Ref ApiKey
    Export:
      Name: !Sub '${AWS::StackName}-ApiKeyId'

  ApiKeyValue:
    Description: API Key 值 (请妥善保管)
    Value: !Sub '请在 AWS Console 的 API Gateway > API Keys 中查看'

